---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-eks
  region: ap-northeast-1

addons:
  - name: vpc-cni # no version is specified so it deploys the default version
    version: latest # auto discovers the latest available
  - name: coredns
    version: latest # auto discovers the latest available
  - name: kube-proxy
    version: latest
