---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-eks
  region: ap-northeast-1

iam:
  withOIDC: true

vpc:
  id: "vpc-id-created-by-tf"  # (optional, must match VPC ID used for each subnet below)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      ap-northeast-1d:
        id: "subnet-pri-1d-id-created-by-tf"
      ap-northeast-1c:
        id: "subnet-pri-1d-ic-created-by-tf"
      ap-northeast-1a:
        id: "subnet-pri-1d-ia-created-by-tf"
    public:
      ap-northeast-1d:
        id: "subnet-pub-1d-id-created-by-tf"
      ap-northeast-1c:
        id: "subnet-pub-1d-ic-created-by-tf"
      ap-northeast-1a:
        id: "subnet-pub-1d-ia-created-by-tf"

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"